### ISSUE TITLE
blue "info" message appears twice on requisitions

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1637] opened 2023-04-28 04:54 UTC
## What went wrong? 😲

![Screen Shot 2023-04-28 at 4 49 59 PM](https://user-images.githubusercontent.com/74992958/235057251-ac5f2847-4de0-40b1-8a3a-bcd8d0b4bfc3.png)

## Expected behaviour 🤔

maybe keep the one on top otherwise headers are really big compared to the table for program requisitions

do we really need to have this information by the way ? Better be a pop window when finalising ? 🤔

![Screen Shot 2023-04-28 at 4 53 18 PM](https://user-images.githubusercontent.com/74992958/235057462-961ac5c2-113f-4661-a0a3-8361f9babbb5.png)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱
 - Version [e.g. 1.2.3]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

**Comment by mark-prins** [comment] 2023-04-28 05:40
duplicate of #1622

**Closed by mark-prins** 2023-04-28 05:40 UTC
Labels: bug, needs triage
