### ISSUE TITLE
"more" info side panel on right of UI breaks tab components

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/open-msupply#777] opened 2022-11-09 03:38 UTC
The tab control underline does not move with resizing of the flex box containing it:

![tab movement bug](https://user-images.githubusercontent.com/7684221/200732286-a19c0b4f-04b3-4471-83b8-8983ed67999f.gif)

You can git similar oddities if you change the browser window width.

**Comment by DhanyaHerath** [comment] 2022-12-06 04:02
Confirmed still a thing! ✅

**Comment by CarlosNZ** [comment] 2022-12-19 00:09
Seems like this is an issue with Material UI itself, so not that clear how to proceed.

There was a bug report for it in 2019 (https://github.com/mui/material-ui/issues/14222), and it has been closed as a similar problem was fixed, but doesn't seem to have fixed this specific issue (where the container is dynamically re-sized).

I've added a comment to the original issue: https://github.com/mui/material-ui/issues/14222#issuecomment-1356907605

Will see if it gets any attention.

Anyone have any other suggestions?

**Comment by mark-prins** [comment] 2022-12-19 02:26
I'm not saying this is elegant.. but it works
Simply add an effect in `DetailTabs` to trigger the windows event which the component is listening for. Adding a debounce allows the animation of the drawer to complete before the tab re-renders

```
import { useDetailPanelStore } from '@common/hooks';
import { debounce } from 'lodash';

...

  const { isOpen } = useDetailPanelStore();
  const handleResize = debounce(
    () => window.dispatchEvent(new Event('resize')),
    100
  );

  React.useEffect(() => {
    handleResize();
  }, [isOpen]);
```

**Comment by CarlosNZ** [comment] 2022-12-19 03:06
Great, thanks @mark-prins .

Looks like we don't need the "debounce" -- the underline indicator seems to have some internal debouncing -- it doesn't start to move until all window resizing has settled down.

**Closed** 2022-12-19 21:56 UTC
Labels: bug, front-end
