### ISSUE TITLE
Store visibility info for facilities do not match in omsupply with Cloud Server

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#988] opened 2022-12-29 07:53 UTC
## Issue Description

Let's take a facilityA which is showing in the Customer List for StoreA (omsupply store). But if we check the store visibility for FacilityA in the mSuppy Cloud Server, the visibility is still OFF. So store visibility info mismatch between mSupply Cloud Server and omsupply?

**Comment by DhanyaHerath** [comment] 2023-01-24 03:19
Possible duplicate of https://github.com/openmsupply/open-msupply/issues/940

**Comment by roxy-dao** [comment] 2023-02-20 01:05
Same as #1085? Okay to close? @mark-prins

**Comment by mark-prins** [comment] 2023-02-20 03:24
Yes, I think that it is. thanks @roxy-dao

**Closed by mark-prins** 2023-02-20 03:24 UTC
