### ISSUE TITLE
Failing to show Response lines

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/open-msupply#144] opened 2022-06-17 06:14 UTC
### Steps to reproduce:

- Make a request order to X site
- Finalise it
- Check on X site response requisition
- The lines are missing

Request line:
<img width="1371" alt="Screen Shot 2022-06-17 at 11 57 39 AM" src="https://user-images.githubusercontent.com/13144882/174236529-08eb71bd-caa9-4498-a245-8612ef72a44f.png">

Response requisition:

<img width="1360" alt="Screen Shot 2022-06-17 at 11 58 21 AM" src="https://user-images.githubusercontent.com/13144882/174236600-fe2a01ea-871a-4bb1-b97e-45d8fc1e52b2.png">

PS: Check @mark-prins for full image.

**Comment by bijaySussol** [comment] 2022-07-04 10:56
thanks
I will try again

**Comment by mark-prins** [comment] 2022-08-01 22:02
closing as unable to reproduce. please re-open if you notice it again.

**Closed by mark-prins** 2022-08-01 22:02 UTC
