### ISSUE TITLE
Sync stops entirely once it is interrupted

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#963] opened 2022-12-16 11:05 UTC
## Issue Description
Once sync is interrupted, now the sync won't work at all.

## Steps I did
1. From omsupply, create a CI/Outbound Shipment.
2. Logged in desktop cloud and checked that CI. 
3. Tried to sync from omsupply. This caused an error, since the transaction was locked (open in cloud)
4. But even after closing it in cloud, opting to Sync won't work anymore!

## Screenshots
<img width="591" alt="Screen Shot 2022-12-16 at 16 49 37" src="https://user-images.githubusercontent.com/59193490/208084890-e60e28ed-2144-4291-9f1d-f63db0109f64.png">

## Expected Behaviour
Like in mSupply Desktop, after unlocking the records (closing the transaction window elsewhere), sync should resume normally!

**Comment by Chris-Petty** [comment] 2022-12-18 22:10
@nisha-dangol great find with the locking, thank you!

**Comment by Chris-Petty** [comment] 2022-12-19 04:44
@mark-prins I was going to write a KDD with mermaidjs sequence diagrams and all that jazz (and ultimately will), but to get things going...

## Opt 1: Just reattempt integration if there was an error from last sync

1. If integration fails on the central server, log it as we currently do and send error response.
2. On next sync, central server reattempts integration if there's an error from the last - proceeds as normal if it goes fine or otherwise returns any errors.

**Pros**: Can do quickly and has no omSupply changes.
**Cons**: Only works in this case with it being a server side record lock. In other cases, If it's always going to fail because the error is due to an invalid body sent, we can't resolve it without manual intervention (which will be bad if 1000 sites have some software bug! Pretty tedious if it's even 1 site in testing tbh).

## Opt 2: Central server throws out the sync_buffer on error

1. If integration fails on the central server, log it as we currently do and send error response. Remote needs to have kept its sync cursor where it was at the start of the sync attempt.
2. On next sync, central server drops all records and allows remote to push them all again, hopefully this time it is fixed.


**Pros**: Can do quickly-ish (I think it's a bad idea and will bite back and take more time 😉). Remotes sites can resolve their problems programmatically in a patch.
**Cons**: Remote has to repush all it's records if only one fails. If this was 10k records, it might be a challenge to repeatedly do this (and/or a big cost in time and data). Likely some awkward state shenanigans holding onto the last _successful_ sync cursor. 


## Opt 3: Replace buffered records when pushing to buffer

1. If integration fails on the central server, log it as we currently do and send error response.
3. On next sync, allow pushing remote records, which replace any existing record in the buffer for the same table and PK. These might include replacing a broken record currently in the central sync_buffer with a valid record.
4. Central server reattempts integration (regardless of the problem record being updated or not) - proceeds as normal if it goes fine or otherwise returns any errors.

**Pros**: Remotes sites can resolve their problems programmatically in a patch.
**Cons**: Needs central server buffer to have overhead of checking if the record is already in the buffer (by table name indexed and PK indexed query) - likely performant enough but will definitely be a big hit.

## Opt 4: New API endpoint for remotes to replace records in the buffer

1. If integration fails on the central server, log it as we currently do and send error response.
2. Remote sites can utilise an endpoint similar to the current "push" end point, which replaces sync_buffer records based on table and PK, in order to resolve the problem record on the central server. (One might suggest differentiating with HTTP `POST` and `PUT`, same same outcome.)
3. Central server reattempts integration (regardless of the problem record being updated or not) - proceeds as normal if it goes fine or otherwise returns any errors.

Pros: Get the best of Opt 2 without compromise on speed in normal sync.
Cons: Likely most complex option - have to make a new endpoint (pretty easy), omSupply needs to implement logic for re-pushing the records that failed to integrate previously first, then.

**Comment by andreievg** [comment] 2022-12-21 01:10
I think so far, with central integration, we only had issues with record `locking`. Re-integration should fix that.

I would suggest we do a hybrid of 1 and 3:

1. If integration fails on the central server, log it as we currently do and send error response.
2. On next sync, central server reattempts integration if there's an error from the last - proceeds as normal if it goes fine or otherwise returns any errors.
3. Store one record per `id` in sync_buffer, using that `id` as primary key (I think this makes update easy ? is there upsert operation from and Object ?)

> Only works in this case with it being a server side record lock. In other cases, If it's always going to fail because the error is due to an invalid body sent, we can't resolve it without manual intervention (which will be bad if 1000 sites have some software bug! Pretty tedious if it's even 1 site in testing tbh).

I wonder if our integration_test for sync in omSupply would be enough to avoid `invalid body sent` type message ?

**Comment by mark-prins** [comment] 2023-01-12 20:49
There are also a couple of related issues, raised in #696 which are worth considering when working on this issue:

- [ ] Processors stops working after a while (can't see any processing in console either and can't quit server, had to close the terminal and delete the database to get it working again)
- [ ] All fields disabled when initialisation error is unknown (not even sure how this error happened in the first place...nothing was displayed in console... might have been a corrupt data file... and sync api is called every second after 👀 ... had to delete browser history to get initialisation working again), refreshing doesn't re-enable the fields either

![image](https://user-images.githubusercontent.com/9192912/212178393-a2733876-d07c-4d1a-bc9e-31c644ae04c7.png)

**Comment by andreievg** [comment] 2023-02-07 23:43
> Processors stops working after a while (can't see any processing in console either and can't quit server, had to close the terminal and delete the database to get it working again)

Would be great to know what happened, but yeah if there is an error it would stop until server restarted, I think server wouldn't quit if there are ongoing requests to the server, like sync status poll)

>  All fields disabled when initialisation error is unknown (not even sure how this error happened in the first place...nothing was displayed in console... might have been a corrupt data file... and sync api is called every second after 👀 ... had to delete browser history to get initialisation working again), refreshing doesn't re-enable the fields either

Once we start syncing the only safe way to restart it is to wipe database, we don't have that functionality automatically and that's the reason fields are disabled (btw they are only disabled once remote server has confirmed that credentials etc.. are correct), I think this behaves as expected

**Comment by andreievg** [comment] 2023-02-08 23:07
Fix for this is on 4d end:

https://github.com/sussol/msupply/issues/12270

**Comment by andreievg** [comment] 2023-02-15 03:10
has PR now: https://github.com/sussol/msupply/pull/12340

**Closed** 2023-03-05 22:09 UTC
Labels: bug, Priority: High
