### ISSUE TITLE
The quantity requested label overlap with the quantity value in the requisition line

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/open-msupply#1724] opened 2023-05-09 05:50 UTC
## What went wrong? 😲
 

![image](https://user-images.githubusercontent.com/11624516/237004820-cca1aa55-af16-4e44-af3f-4d1e4c606414.png)

It happens in French as well as in english

## Expected behaviour 🤔

The quantity value should be visible

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Open a requisition
2. Click on a requisition line
3. See error. Requested quantity label overlap with the quantity field obscuring the actual value

## Your environment 🌱

 - Version: 1.1.11
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [x] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by bijaySussol** [comment] 2023-05-09 15:29
Duplicate of this possibly @alainsussol 
https://github.com/openmsupply/open-msupply/issues/1572

**Comment by mark-prins** [comment] 2023-05-09 20:25
duplicate, thanks @bijaySussol

**Closed by mark-prins** 2023-05-09 20:25 UTC
Labels: bug, good first issue, front-end, Section: Requisition, platform: desktop, needs triage
