### ISSUE TITLE
Can't add items from Master List on Outbound Shipment

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/open-msupply#263] opened 2022-07-04 01:50 UTC
User is unable to add items from a Master List to an Outbound Shipment. 

Fails with toast: 

![image](https://user-images.githubusercontent.com/19318937/177067850-9c56877d-3839-4fd8-b0b8-23b7b964b551.png)

Repro: 

1. Create a new Outbound Shipment
2. Click 'Add from master list' button
3. Error appears

Note that Master Lists with items do exist for this client: 

![image](https://user-images.githubusercontent.com/19318937/177067898-f9bb0417-1872-4bdf-b8cc-91d1dac0038e.png)

**Comment by mark-prins** [comment] 2022-07-04 01:58
duplicate of #203

**Closed by mark-prins** 2022-07-04 01:58 UTC
