### ISSUE TITLE
finalising a requisitions: warning message not clear enough

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1754] opened 2023-05-12 14:33 UTC
## Is your feature request related to a problem? Please describe 👀

it's too tempting to click on the "Finalise" button when setting the supply quantity while the user should instead create a new outbound shipment. 

Big risk that user will finalise a requisition without creating an outbound shipment. 

<img width="1500" alt="Screenshot 2023-05-12 at 5 29 53 PM" src="https://github.com/openmsupply/open-msupply/assets/74992958/778fb320-bfda-433d-af0c-60d05d827602">

## Describe the solution you'd like 🎁

if supply quantity > 0 OR remaining quantity > 0, user should be clearly warned that he is about to finalise a requisition with still some remaining quantity to supply and that he should create an outbound shipment to fulfil the customer request. 

### Describe alternatives you've considered 💭

If supply quantity > 0, user should even be offered to create an outbound shipment for the set supply quantity when clicking on finalising. 

### Moneyworks Jobcode 🧰

DJ

**Comment by richardmoizeau** [comment] 2023-05-12 14:34
@Pauline-mSupply

**Comment by mark-prins** [comment] 2023-05-12 22:30
possibly duplicate of #1737? If yes, can I close this one?

**Comment by richardmoizeau** [comment] 2023-05-13 02:51
> possibly duplicate of #1737? If yes, can I close this one?

Yes it is!

**Closed** 2023-05-13 03:05 UTC
Labels: enhancement, needs triage, make omSupply delightful
