### ISSUE TITLE
Duplicate stock lines created when received in an inbound shipment

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#1049] opened 2023-01-18 23:11 UTC
### Found in Pauline and Damon's testing: 

When they receive an inbound shipment, each item that they receive shows up twice when they view stock. 
It also shows up when they try to issue stock, so for example, if they receive 2 packs of 40, it will show up as 2 separate stocklines - both saying 2 packs of 40, so they then have 4 packs of 40. 

### Setup
On android tablets, using Timor Leste datafiles

## OTHER
Andrei says it's when you manually change statuses rather than going straight to finalised

**Comment by andreievg** [comment] 2023-01-19 07:03
Oki, after some further digging around, the root of the cause is not what I expected. This would happen if tax is set on invoice and then if we go to delivered and then verified on inbound shipment. Sorry I wasn't able to review the tax work, it's pretty apparent now what the issue is (invoice line changes are overwritten by invoice line tax update changes in inbound shipment `generate`, stock_line_id is wiped out and when verified new stock_line is generated). 

Why does this show up in transfers ? Basically `tax` is not nullable in mSupply, so when invoice is transferred the `tax` becomes Some(0.0) instead of usual None, at which point the invoice_line tax adjustment logic fires when update happens.

I'll assign to @roxy-dao, since she knows other areas where this could be problematic. 

To solve the issue:

* Add tests to replicate this behaviour.
* Look at other areas where this could be potential problem and add tests there.
* Update logic so that test pass.

(by tests in this case I would imagine a tax update on invoice at the same time as updating invoice to `delivered` status or from `delivered` to verified status, making sure invoice_line and batch are generated correctly, and invoice_line retains stock_line_id), [maybe something like this](https://github.com/openmsupply/open-msupply/compare/Example-tax-update-causing-test-fail) (but also including a test that invoice_line pricing were updated)

**Closed** 2023-01-25 22:24 UTC
Labels: bug, Priority: High
