### ISSUE TITLE
omSupply report printing problem in oms apk

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#1337] opened 2023-03-13 10:47 UTC
## What went wrong? 😲
oms report do not work in oms apk tablet(while the same is working fine for oms desktop server )

## Expected behaviour 🤔
Report should print properly

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Setup a oms server on mobile tablet properly
2. In mSupply CLoud server, add the appropriate `omSupply` report through Report Manager (I'm adding Stocktake report for example)
3. Back in our OMS apk, create a stocktake
4. Print
5. See error: bunch of multiple irrelevant pages showing up instead of the exact report

## Your environment 🌱
 - Version : oms apk: v1.1.4 with mSupply Server: v7-03-1
 - Platform : tablet
 
## Screenshots
![Screenshot_20230313-162502](https://user-images.githubusercontent.com/59193490/224680058-cd572416-fb78-4dce-b4f9-29d8ed05cec9.png)

**Comment by DhanyaHerath** [comment] 2023-03-13 18:10
Duplicate of https://github.com/openmsupply/open-msupply/issues/1316

**Closed by DhanyaHerath** 2023-03-13 18:10 UTC
Labels: bug
