### ISSUE TITLE
New Patient modal fields are not consistent with the Patient Registration form

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1090] opened 2023-01-25 04:28 UTC
### Dispensary > Patients > New Patient > New Patient Modal: 
- [x] there is no validation for the National Health ID (should be 10 characters, numerical only): 
<img width="1320" alt="Screen Shot 2023-01-25 at 2 11 20 PM" src="https://user-images.githubusercontent.com/74992958/214478213-b2a2af08-bc22-42a1-94a1-6362c7bc656f.png">

- [x] no validation for DOB:
<img width="462" alt="Screen Shot 2023-01-25 at 2 12 29 PM" src="https://user-images.githubusercontent.com/74992958/214478170-666876b8-b11d-4297-8cca-a15808cc3b7e.png">

- [x] Gender dropdown of the modal should be the same as the one in the patient registration form
1. Patient Registration Form
<img width="410" alt="Screen Shot 2023-01-25 at 2 14 15 PM" src="https://user-images.githubusercontent.com/74992958/214478456-38b4089b-60f5-4fe2-a6c9-6ebe8d9bc826.png">

2. New Patient Modal
<img width="394" alt="Screen Shot 2023-01-25 at 2 14 07 PM" src="https://user-images.githubusercontent.com/74992958/214478462-7e809dca-1dcc-4679-8e9c-db9b1025d98f.png">

**Comment by clemens-msupply** [comment] 2023-02-03 01:56
Duplicate of #867

**Closed** 2023-03-02 20:02 UTC
Labels: bug, programs, Priority: High
