### ISSUE TITLE
Item name not showing correctly while selecting the items in internal order

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#961] opened 2022-12-16 07:18 UTC
## Issue Description
In omsupply, while creating an internal order, we can see that selecting a item line, some items do not display item name (leaving it blank. see screenshot). It is weird that for some items, it is displaying correctly.

## Steps to Reproduce
1. In omsupply, create a internal order.
2. Add items from a master list
3. Click some items to add requested quantity.
4. See error: for some items, the name is not displaying, as in the screenshot below

## Screenshot
<img width="999" alt="item name missing" src="https://user-images.githubusercontent.com/59193490/208044176-1440af54-abf7-4432-89e3-abe2d8a04fa3.png">

See the recording as well: https://recordit.co/hBeGg5KuCy

## Expected behavior
The item name should appear properly for all the items selected.

**Comment by mark-prins** [comment] 2023-01-10 19:54
Duplicate of #896 and fixed with #897 etc

**Closed by mark-prins** 2023-01-10 19:54 UTC
