### ISSUE TITLE
Sorting Outbound shipment sorted by some column, the listbox UI get changes unlike with others

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/open-msupply#159] opened 2022-06-20 05:04 UTC
Sorting Outbound shipment sorted by created date, the listbox UI get changes unlike with others

### Steps to reproduce:

- Setup `mono-repo with central server`
- View the Outbound shipment
- Sort by Status / Created -> The  listbox width is increased
- Resort by Comment -> It is back to original

Original window:
<img width="1361" alt="Screen Shot 2022-06-20 at 10 48 48 AM" src="https://user-images.githubusercontent.com/13144882/174528785-2ea28662-99da-4956-9b20-c3c7671f6f36.png">

After sorting by Created column:

<img width="1360" alt="Screen Shot 2022-06-20 at 10 49 17 AM" src="https://user-images.githubusercontent.com/13144882/174528827-b25ca796-ba16-42f0-92ef-d3f3e893122c.png">

**Comment by mark-prins** [comment] 2022-07-01 05:42
tested on chrome and firefox with a variety of screen sizes and can't reproduce. Is someone else able to?
Or provide more details?

**Comment by mark-prins** [comment] 2022-08-03 05:28
Closing as unable to reproduce. please reopen if required

**Closed by mark-prins** 2022-08-03 05:28 UTC
