### ISSUE TITLE
Logical document clock

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#123] opened 2022-06-13 23:38 UTC
Problem: if there is clock skew between two sites a user might seemingly not be able to update a document version for a certain amount of time.

For example, if clock A is ahead of clock B by 20 the document version A at t=50 stays ahead even when we know that a document at B (t=40) changed after A (because we know about the change at A). This would be very confusing because edits will not show any effect till B caught up with A.

Solution: use a logical clock in addition to the site local clock.
The logical clock value is `max(clock, latest logical clock value) + 1`
This make sure the local logical clock is always ahead of the latest known logical clock from a remote site.

The logical clock is very simple to implement:
- Query the document with the latest logical clock value
- When updating a document use `max(clock, latest logical clock) + 1` as the document's logical clock value 

Example: A is ahead of time by 20 and during a sync Site B learns about documents from A and updates its logical clock if needed:

| comment             | event A | logical clock A | clock A | event B | logical clock B | clock B | real time |
| ---                 | ---     |             --- |     --- | ---     |             --- |     --- |       --- |
|                     | v1      |              31 |      30 |         |                 |         |        10 |
|                     |         |                 |         | v2      |              41 |      40 |        40 |
| sync  1             |         |                 |         |         |              46 |      45 |        45 |
|                     | v3      |              91 |      90 |         |                 |         |        70 |
| v4 sorted before v3 |         |                 |         | v4      |              81 |      80 |        80 |
| sync  2             |         |                 |         |         |              92 |      85 |        85 |
| v5 now sorted after v3  |         |             109 |     108 | v5      |              93 |      88 |        88 |
| B caught up         |         |             114 |     113 | v6      |              94 |      93 |        93 |

In this example:
- v4 will be (wrongly) sorted before v3, however, there is no way to fix this because the real time clock is unknown and its impossible to say which clock was/is correct.
- After sync 2, v5 will be correctly sorted after v3 even though clock B is still behind clock A.
- In the last step the clock from site B caught up with its local clock

As an alternative the central server could keep track of time differences during sync but this becomes more complicated and is error prone (e.g. if connection has high latency).

**Comment by jmbrunskill** [comment] 2022-06-14 02:23
If we used a [Lamport Clock](https://en.wikipedia.org/wiki/Lamport_timestamp) per document and still assumed that the time stamp is likely to be correct I would expect behaviour something like this.

I think incrementing the logical clock on record creation rather than every second but haven't got my head around the implications of a logical clock that updates aligned with realtime.

Action | event A | Parent | logical clock A | clock A | event B | Parent | logical clock B | clock B | real time | Comment
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Initialise |   |   | 0 | 0 |   |   | 0 | 0 | 0 | Logical clocks start at 0
A Creates a Record | v1 | None | 1 | 30 |   |   |   |   | 10 | Every time and actor creates a record they increment the logical clock first
B Creates a Record |   |   |   |   | v2 | None | 1 | 40 | 40 | Now Actor A and B have both created a record at logical clock 1
Sync |   |   | 2 |   |   |   | 2 | 45 | 45 | At sync time B, both actors assume V2 is latest due to it's clock being ahead (record timestamp) and the same logical clock
A Creates a Record | v3 | v2 | 3 | 90 |   |   |   |   | 70 | Actor A creates V3 but with incorrect future timestamp
B Creates a Record |   |   |   |   | v4 | v2 | 3 | 80 | 80 | Actor B creates v4 with correct timestamp and incremented logical clock
Sync |   |   | 4 |   |   |   | 4 | 85 | 85 | Since V3 has the same logical clock and the highest timestamp it is considered latest by both actors
B Creates a Record |   |   | 5 | 108 | v5 | v3 | 5 | 88 | 88 | V3 was the highest clock previously so becomes the parent record
B Creates a Record |   |   | 6 | 113 | v6 | v5 | 6 | 93 | 93 |  
Sync |   |   |   |   |   |   |   |   |   | Both actors now consider v6 to be the latest

I think this could work something like this:

1. On every record creation, increment the logical clock for the document and record the timestamp
2. At sync time process any incoming records one by one. 
   * If the record's logical clock is < your logical clock store record assume yours is the latest
   * If the record's logical clock == your logical clock assume the one with highest timestamp to be latest
   * If the record's logical clock is > your logical clock assume theirs is the latest
 3. Update document's logical clock to be the max logical clock you've seen so far

This obviously has issues is one actor creates more than 1 version remotely, before your create your local record.
However, I'd argue that this would be very rare, and this would satisfy the requirement that it's easily fixed by simply saving a fixed record.

I also think that the one by one record processing (2 in the list above) can essentially be removed by simply storing all records and querying for the latest record using a statement something like:

`SELECT * FROM document_versions WHERE document_id = 'DOCID' ORDER BY logical_clock desc, timestamp desc LIMIT 1`

This to me meets the goals of, working for the majority of cases, relatively simple, allowing users to correct errors when they do occur.

With Andrei's example from #88 we'd still get the same outcome (*I think*)
However, if an uneven number of versions had been created between sync events, the site that had created more records would be assumed to be the latest. I personally think this is acceptable assuming that concurrent edits on multiple sites is rare.

Any thoughts? Does this sound like a good solution? Easy to understand?

**Comment by jmbrunskill** [comment] 2022-06-14 02:55
A couple of quick comments on my proposal above...

 * I think it really requires a per-document logical clock, as the assumption that multiple edits on different sites will be rare doesn't hold if the clock spanned across the whole site.

 * I really love the idea that the remotes sites don't really need to do anything smart to handle this, they can just save every record as it comes in and use the database sorting to correctly identify the latest record. Of course they need make sure they increment the logical clock when saving the doc as well but that's about it.

**Comment by andreievg** [comment] 2022-06-14 04:15
`OPTION 1`

Thanks Clemens, I'll try to look at it in depth, I think we have a lot of scenariors to consider. 

> The logical clock is very simple to implement:

I think with simple solution, you should be able to consider all uses cases with ease, for this solution it's very hard because it spans across multiple sites, here is use case which results in undesirable outcome:

* If you have three sites, A, B and C, and A is way ahead in time but B and C are accurate. Once A and B inherit A's logical clock, their own clock is irrelevant (they now rely purely on increments, the 50/50 scenario I was referring to in our meeting, especially if logical clock is incremented by any document change, but still apparent if increment is only by document 'instance').

Above example is not really to invalidate the option, but to try and validate my disagreement with claims of simplicity.

I think @jmbrunskill solutions deals with the problem outlined above, but with a small side effect that he identified (more then one version created remotely, which technically can also be dealt with by record sync iteration vs on event, but it adds more complexity (i.e. logical clock on new documents = logical clock on documents from other site + 1) <- this is still per document 'instance'. (but another use case, if local time has changed backward, local documents might not be editable)

I would still like to question, did we really think of all of the use case that can happen in sync (merging of patients,  etc..) ?

I really like dealing with the **root cause** rather than trying to fix **side effects**. So the root cause = records being saved and sent to propagate through sync system with incorrect timestamp, consequences:
1- Inability to edit this record in any other side if one site time is ahead in the future and they've edited a document (we would select latest document always)
2 - If current site time is set in the past, then they might not be able to edit their own documents.

Subjectively, I think the simples way to deal with consequences 1 and 2 (still dealing with side effects) is to do search by latest amongst branch ends of document instance (i.e. where ID is not referenced by any other document parent_id), this is still not accurate but is the simplest (and I think good compromise, might require multiple edits thought to get it up to speed if there are multiple branch ends that are ahead of current site).

But to deal with root cause, would require a little bit more, but since it happens __on only one site__ I think it's much easier to reason about (reason about = think of all of the use cases):

`OPTION 3`

* If system time is ahead or behind of central server time by a defined margin, we show this in UI (this needs to be dealt with), I would even disable any operations if this problem is evident.
* Cannot sync if system time and  central server time is out by defined margin (UI will show this), central server rejects sync, based on system timestamp in the header.
* Server reject any records with timestamps later then central server time (UI will show this)
* When above error is shown, sync cannot proceed and error in UI points out 'what to do'
* 'What to do' is a button in admin ('fix timestamps...') which just sets any timestamps that are 'ahead' to current system time (for document it will have to invalidate document, and put a duplicate in it's place, even though this would mean messy document branching)

`assumption`: Central server time always has connection to internet and manual misconfigurations deal with much bigger problems then this and we definitely can't deal with all of those use case progamtically, so we can make an assumption that it's configured correctly with correct date and time.

Option 3 can work for other records.

**Comment by jmbrunskill** [comment] 2022-06-14 04:53
`OPTION 2`

> (but another use case, if local time has changed backward, local documents might not be editable)

I'm not sure I understand your meaning here, if you are creating a document locally, it will always be created with the highest logical clock +1 so a new document will always appear as the latest locally.

`OPTION 3`
I think I like this idea, can I clarify how we'd query this latest record though? Would you do something like this?

`SELECT * FROM document_versions dv WHERE document_id = 'DOCID' AND id not in (SELECT parent_id FROM document_versions dv2 WHERE dv.document_id = dv2.document_id) ORDER BY timestamp desc LIMIT 1`

I think this would work well and have similar properties to `Option 2` except for as you mentioned if there are multiple branches ahead of current site time. It would also have the property that a locally created record with a more recent timestamp would still be the latest even if multiple new documents are created from another site (Which is we assume timestamps are correct is a good thing)

**Comment by andreievg** [comment] 2022-06-14 05:17
> I'm not sure I understand your meaning here, if you are creating a document locally, it will always be created with the highest logical clock +1 so a new document will always appear as the latest locally.

I've rephrased it, it refers to a variation suggestion but it's badly explained

**Comment by clemens-msupply** [comment] 2022-06-14 23:11
@jmbrunskill the only difference from Option 1 to Option2 is that I "virtually" increase my logical clock till I reach my local clock (to avoid letting the site win who did the most edits even if both sites have synced clocks). So Option 1 uses an equivalent to a Lamport timestamp... Or do I miss another difference?

Option 3 seems to work only in some cases (but I like the idea because if we find all heads we can also just refer to multi parents  in an edited document which avoids this problem :-) )

Option 4 is a good to have but doesn't really solve the underlying problem but just mitigates it.

`document_version` sounds good to me

Some general observations:
- think we should really try to avoid making assumptions of the "likeliness" of events. These rare events usually happen more often than you think and can cause unexpected problems if not handled.
- there is a base complexity; we simplified one part of the system by removing the merge which shifted the complexity to this problem

**Comment by andreievg** [comment] 2022-06-15 00:38
> Option 4 is a good to have but doesn't really solve the underlying problem but just mitigates it.

Yep, it doesn't solve it, I think i used the term `deal` (I don't think you can `solve` or `prevent` it, unless connection to internet is consistent and stable, which is definitely not guaranteed),

> think we should really try to avoid making assumptions of the "likeliness" of events. These rare events usually happen more often than you think and can cause unexpected problems if not handled.

If this refers to my last comment about central server configurations, I would disagree, we have to make that assumption, otherwise we have to deal with a lot of use cases (too many permutations of misconfigurations to comprehend)
And I am certain that we can put less effort/code in resolving some edge case scenariors (i am less worried about effort, and more worried about code, want to avoid `write only code`) . i.e. If it doesn't happen a lot then it's ok to resolve it in simple but not `perfect` way (unless the perfect way is just as simple to do)

> Option 3 seems to work only in some cases

`All` options work in only some cases, I've outlined problem with Option 1 with a use case. And James outlined issue with Option 2.

> we can also just refer to multi parents in an edited document which avoids this problem

Nope, same problem, when new head arrives. (it's less of a problem if we record multi parents, but it makes less sense data wise, since new document is based of one parent)

> there is a base complexity; we simplified one part of the system by removing the merge which shifted the complexity to this problem

I think the suggestions that merge entirely solves the issue of one site being ahead in time is not true. With merge you still take latest timestamps as priority (and if we do merge purely based on parent/branch relation then we completely discard the timestamps, and latest sync always wins, which is what our existing system does). In terms of timestamp issue, merge only helps with one use cases that option 3 doesn't, if more than 3 sites editing the same patient and two of the site times are ahead, site 3 would need multiple edits with option 3 to show the changes, whereas with merge it needs 1 edit to show the changes.

Personally, I am more in favour of Option 4, because:
* it deals with issue at the root (and stops it from propagating to other sites, causing more use cases to deal with)
* it can work for other areas affected by the same problem.
* gives admin user an opportunity to actually solve the problem for future operations.
(a bit like having a sieve at the source rather then picking out impurities at the point of consumption)

**Comment by jmbrunskill** [comment] 2022-06-15 01:18
> Some general observations:
> 
> * think we should really try to avoid making assumptions of the "likeliness" of events. These rare events usually happen more often than you think and can cause unexpected problems if not handled.
> * there is a base complexity; we simplified one part of the system by removing the merge which shifted the complexity to this problem

Good observations @clemens-msupply 
I agree that making assumptions about likeliness is dangerous, and even a rare event can have a big effect.
I personally I like the approach I think we are trying to take though, e.g. trying to evaluate the risk, and the consequences and looking at options to reduce the overall risk. 

It could be thought about much more formally and it might help us though?

At other organisations I've worked with a 'risk matrix' has been used to help evaluate these situations.
Here's an example from NZTA:
https://www.nzta.govt.nz/roads-and-rail/rail/operating-a-railway/risk-management/risk-matrix-likelihood-and-consequence-tool/

When you're evaluating a risk you have 3 main choices.
1. Accept the risk and consequences as they are 
2. Try to reduce the likelihood of the consequence
3. Try to reduce the consequence if the issue does occur

Obviously in software there are some solutions that can almost eliminate the risk which are good to evaluate, but we also need to take into account the costs of mitigation and elimination.
To take an extreme example, if it was going to cost us $1million to design, implement and test the perfect solution we probably can't afford to invest that much money. On the other hand for Google, that investment it might be worth it.

I think we definitely need to understand that some problems like you say have an underlying complexity and a perfect solution might not exist, or be intractably hard (e.g. we probably don't want to invest in an AI based merge tree resolver).

Additionally we need to recognise that we won't identify all the risks, likelihoods, and consequences so even if we are a bit more formal with our evaluation process, mistakes can still be made :)

In this case `OPTION 0` here might be to document that problems will occur if there is clock drift and simply accept the consequences of that. Like @andreievg has raised, if we have significant clock drift between sites a lot of other records outside of document sync are affected which so far have been accepted by our stakeholders.

At the very least I'd like to see some process for altering administrators to the incorrect system clock issue.

**Comment by clemens-msupply** [comment] 2022-06-16 00:56
I made a figure to illustrate the problem a bit better. In this case Site B and Site C have the same clock and Site A's clock is late. Changes from Site B and C are know to Site A and Site A makes some further local changes (V4 and V5) which are both still behind the time from Site B and Site C. The logical clock and the merge both keep the total order.

![2022-06-14_logical_clock drawio](https://user-images.githubusercontent.com/88299195/173966641-f164769f-e36f-4858-ba6d-89813e644f5e.svg)

@jmbrunskill was just about to put the problem into the matrix with an estimated cost but I realized this would probably very debatable as well...

**Comment by andreievg** [comment] 2022-06-16 13:00
Thanks, those diagrams are very helpful in summarising some use cases mentioned. There is one use case missing for logic clock (Option 1), that I've mentioned (see diagram below). And don't take into account dimension of 'timing' of sync, like if merge option site v3 synced after v4 edit, it would still require to 2 edits on Sita A to see the changes (see diagram below, sorry this kind of a biased use case for Option 3, but I think above example is biased against Option 3).

![Screen Shot 2022-06-17 at 12 52 13 AM](https://user-images.githubusercontent.com/26194949/174073737-933a5692-21b4-4611-a9f4-5da6236f02c3.png)

There is no such thing as `perfect` solution (even medical equipment that maintains some people's live has a target error percentage), for erroneous use cases, it's always likeliness * consequence vs effort * complexity in my books.

I still go for Option 4 (or some variant of it, i am happy with just informing administrator), lots of use cases (no perfect solution), very rare.

**Comment by clemens-msupply** [comment] 2022-06-16 21:25
Yes the case you mentioned is exponentially harder to solve, i.e. syncing clocks on two sites is very hard. To fully solve it you would need special hardware and I totally agree Option 4 is the best and practical thing we can do about it to keep the time delta small.

In this issue we have a simpler problem which is: a site knows about some previous edits; makes some changes but the changes don't show up (on the site) because an existing document (on the site) has a newer timestamp. The logical clock (and the all head merge) use the knowledge about existing documents prior to the edit to order new document after existing documents.

Effort and complexity are IMHO both small for the logical clock and merging heads and you get a more robust solution.

**Comment by andreievg** [comment] 2022-09-28 22:24
Closing issue, can be re opened, we have it for reference

**Closed by andreievg** 2022-09-28 22:24 UTC
Labels: programs, back-end
