### ISSUE TITLE
Ability to create an encounter right after enrolling a patient

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#764] opened 2022-11-06 22:05 UTC
In most cases, a patient is first registered, enrolled and may have its first encounter right away. Would save user time to be able to create an encounter for the program the patient just enrolled into when saving enrolment form. 

Suggestion: 
when saving enrolment form, a pop-up window confirming that patient data has been saved and offering the possibility to create an encounter: 

[Patient First Name] [Patient Last Name] is now enrolled in the [Program name]. Would you like to create a new visit for this patient ? 
Right button = Yes
Left button=No (default)  

What do you think ?

**Comment by roxy-dao** [comment] 2023-03-28 20:32
Duplicate of #1379

**Closed by roxy-dao** 2023-03-28 20:32 UTC
Labels: programs, Priority: Low
