### ISSUE TITLE
Patient contact data is edited without user input

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1110] opened 2023-02-01 01:46 UTC
When opening a patient without contact data an empty object gets added automatically:

![Image](https://user-images.githubusercontent.com/88299195/215924577-bfb84c3a-9dc8-4201-837d-7b151891b04d.png)

Thus the user can't leave the screen without a warning. This behavior should be suppressed...

**Comment by CarlosNZ** [comment] 2023-02-01 23:21
Ah right, the problem is that the "FirstItemArray" component always creates a first item regardless of whether there is any data, whereas the regular Array component only creates items as they are added.

However, this should be created during the initial Patient creation, so it won't change in later viewings. Have you found a case where it gets created with an empty array, and is changed later?

I could add some logic to the FirstItemArray component to check if there is any valid data in the item and empty the array if not, but I'm just wondering if this is necessary since we shouldn't see this problem in normal usage.

**Comment by CarlosNZ** [comment] 2023-02-01 23:40
Yeah, I'm not sure this can be changed very easily. The "FirstItemArray" will *always* create a data array with a single empty object as the child JSONForms component (which always exists in this component) must have at least an empty object as _its_ data.

But as I said, this shouldn't be a problem as it'll be created like this when the patient is first created, so it shouldn't change after that.

What do you think @clemens-msupply ?

**Comment by clemens-msupply** [comment] 2023-02-08 01:07
Yes we can add the contact item to the auto generated patients (at least to fix the issue).

Do you know if this was working before? or is it because of some recent array changes? Think it would be good if the component doesn't edit the data without user input... Where is the insertion of the empty object happening?

**Comment by CarlosNZ** [comment] 2023-02-08 01:14
> Where is the insertion of the empty object happening?

It's in the "FirstItemArray" component, which is structured as an array with a single (object) item in it. And the contents of the object is entirely determined by a child JSON Forms instance, so we don't have control of that from the FirstItemArray itself. And that component doesn't even have its own "handleChange" method, as it's just done from the the child element, so it would be quite fiddly to overcome this without restructuring how the FirstItemArray component works.

**Comment by clemens-msupply** [comment] 2023-02-08 01:59
Yes had a quick look and can't see an easy way either... so just updating the current init script would work....

**Comment by CarlosNZ** [comment] 2023-03-01 20:16
Closed by #1257

**Closed by CarlosNZ** 2023-03-01 20:16 UTC
Labels: programs, Priority: Normal
