### ISSUE TITLE
Duplicate orders retain data from previously existing numbered requisition

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#962] opened 2022-12-16 10:41 UTC
## Issue Description
When you initialise an existing store as omsupply, it turns out that the new transaction starts with No. 1. 

For eg, create a new internal order, it'll be No. 1 and if there is already another previous Order No. 1, then you'll notice this weird behaviour: no matter what name you choose this time, it'll show the data of the previous Order No. 1.  
Go back to Orders List and now you'll see the Name you selected, but when you open it, it still persists the data from initially existing Order No. 1 

## Screenshots
See this [recording](https://recordit.co/oa9LVzgb74).

**Comment by Chris-Petty** [comment] 2022-12-19 01:40
@nisha-dangol @andreievg I believe this issue will be resolved with https://github.com/openmsupply/open-msupply/issues/811. The problem is number sequences don't sync and currently they'll start from 1 again. When omSupply frontend requests the information for the specific requisition you've clicked, it uses the serial number rather than the primary key (to keep the URL tidy!). It must be getting the first record that matches the serial number which will be the original one, not the new one.

On that note - I'll flag that this issue gets fixed when the other other issue's PRs fix it.

**Closed** 2022-12-21 20:12 UTC
