### ISSUE TITLE
[Deployment Feedback] Outbound shipment - Scanner button acting differently from before

### ISSUE THREAD

**Issue by Pauline-mSupply** [openmsupply/open-msupply#1821] opened 2023-05-22 20:41 UTC
## What went wrong? 😲

When trying barcode scanning , a user created a new outbound shipment for their patient. 
When the new outbound shipment window opens, there is a button "Scanner". 
The user clicks on it. The button then changes to _stop_. 
The user then uses the barcode scanner which beeps when a barcode is found. 
Then nothing appears on screen. 
The user has to click on _Scanner_ again (which has changed from _Stop_ to _Scanner_ again )
Then the window with the associated item appears. 
Then normal process : add quantity, click okay, finalise, etc. 
SITE : POLYCLINIQUE YONIS TOUSSAINT - PHARMACIE

## Expected behaviour 🤔
It's hard to define those as expected behaviour but before the steps were :

1. Create outbound shipment, choose a customer 
2. Click on _Scanner_ the button turns to _Stop_
3. Scan the barcode with the barcode scanner
4. a window opens with the correct item 
5. The user chooses quantity, clicks okay, finalises and all is good in the world

The unusual behaviour above is not a massive issue since it is what a user does naturally but 1. it's not ideal and 2. this change in behaviour may hide a bigger issue and this is why I wanted to mention it here. 

## Your environment 🌱

 - Version: Open mSupply v1.1.13 (version before May 22nd)
 - Platform:
   - [ ] android (tablet)
   - [] browser (extra points if you tell us which one)
   - [X ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)
 
@richardmoizeau

**Comment by mark-prins** [comment] 2023-05-24 06:05
Fixed with #1837 
Sorry, created a duplicate of the issue.

**Closed by mark-prins** 2023-05-24 06:05 UTC
Labels: bug, Priority: Normal, needs triage

**Comment by Pauline-mSupply** [comment] 2023-05-24 11:10
@mark-prins : hi there, it seems that the bug is still here.
