### ISSUE TITLE
Searchable field for mother's program ID

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1214] opened 2023-02-20 21:23 UTC
Carry over from #1151, probably links in with #1061

#### `Mother's Patient ID`: 
- [ ] `HIV Program ID of the patient's mother`. Dependent field: it should only be visible and entered if patient is an infant (less than 2 years old). Since there is only one field in that section, I'd move it to the top section (see below): 

![Screen Shot 2023-02-08 at 5 13 58 PM](https://user-images.githubusercontent.com/74992958/217432316-4fc80af1-9b7e-4e5a-9b59-e26c453e6a9b.png)

`HIV Program ID of the patient's mother` - 2 options: 
- user manually enters the mother's program ID 
- user can select a Program ID in a Drop Down List that contains all Program ID of patients registered in this clinic (as a way to connect 2 patients records together). The infant's mother is always a registered patient with a HIV program ID.

**Comment by CarlosNZ** [comment] 2023-02-20 21:26
Duplicate of #1070 (Currently in progress)

**Closed by CarlosNZ** 2023-02-20 21:26 UTC
Labels: programs
