### ISSUE TITLE
Patient form prompts re changes when unchanged

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1212] opened 2023-02-20 20:00 UTC
## What went wrong? 😲
 
1. View a patient
2. Click on the `Encounters` tab
3. This:
<img width="510" alt="Screenshot 2023-02-20 at 1 06 56 PM" src="https://user-images.githubusercontent.com/9192912/220189523-b44b0212-fa35-45d8-99cc-ccc7a58550d2.png">

It's annoying me. And unnecessary, I think.

**Comment by CarlosNZ** [comment] 2023-02-20 20:30
This is a duplicate of #1110 

See [this comment](https://github.com/openmsupply/open-msupply/issues/1110#issuecomment-1412895727) and the one below it for an explanation.

Any patient created by a user won't have this problem, as the data shape will already be like this, so we just need to add this structure to "built-in" patients (or come up with another solution).

**Closed by CarlosNZ** 2023-02-20 20:30 UTC
Labels: bug, programs
