### ISSUE TITLE
Encounter status UI updates

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#1283] opened 2023-03-06 02:38 UTC
Rules for Status to be clarified.

(e.g. start scheduled, changed to "missed" once date has passed. Allow user to change to "DONE" or "CANCELLED")

**Comment by DhanyaHerath** [comment] 2023-06-02 01:03
Closed as duplicate of https://github.com/openmsupply/open-msupply/issues/1575

**Closed by DhanyaHerath** 2023-06-02 01:03 UTC
Labels: programs, Priority: Normal
