### ISSUE TITLE
Stock transfer invoice

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/open-msupply#1239] opened 2023-02-26 17:41 UTC
## What went wrong? 😲

Stock transfer either by outbound invoice or via internal order request > response, Viewing inbound shipment in remote client, complaints says `Int parsing error`.

![invoice -1](https://user-images.githubusercontent.com/13144882/221426911-85947c20-7c4e-4163-ba31-9bacb826e892.PNG)

## Expected behaviour 🤔

Not sure what is the idea behind, probably central server logic need changing or the remote client should be handling it.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Do either, normal stock transfer or request, response order work flow
2. Once the response is sent from responder (Internal order work flow), or outbound invoice is finalised > Creates its associated Supplier invoice
3. Sync remote client
4. See inbound shipment
5. Click to view details
6. Int parse error

## Your environment 🌱
 - Version [1.2.3 , current develop]
 - Platform [browser, windows desktop, server]

**Comment by andreievg** [comment] 2023-03-10 04:22
The site you are transferring to, is it new site or existing mSupply site that was upgraded ? 
With syncV5 changes, this should only happen if site is misconfigured, (central thinks the site is mSupply rather then omSupply), you can check that in `synchronisation` form, if site is `remote_server` it's omSupply site

**Comment by bijaySussol** [comment] 2023-03-10 12:21
> The site you are transferring to, is it new site or existing mSupply site that was upgraded ?
> With syncV5 changes, this should only happen if site is misconfigured, (central thinks the site is mSupply rather then omSupply), you can check that in `synchronisation` form, if site is `remote_server` it's omSupply site

I am using the same datafile which is hosted on demo omsupply, it's a existing site from that datafile.
Site setting:

<img width="498" alt="Screen Shot 2023-03-10 at 6 05 53 PM" src="https://user-images.githubusercontent.com/13144882/224314703-0f79e4a3-656d-42c8-838f-4ea1e70d0bda.png">

Mis-configured?

**Comment by anildahalsussol** [comment] 2023-03-16 09:47
@andreievg @bijaySussol: Here the invoice number is -1 and in the backend it's expecting u32. I think in the method get_invoice_by_number. Should we change to i32 ?

**Comment by bijaySussol** [comment] 2023-03-16 10:13
@anildahalsussol : 
I am happy for you to take a lead on this one.
But, @andreievg would be the best one to call this as it seems from this comment; https://github.com/openmsupply/open-msupply/issues/1239#issuecomment-1463233239 this should not happen in first place, but i see it happening.

**Comment by anildahalsussol** [comment] 2023-03-16 10:28
It will happen coz it's looking for unsigned numbers in the backend. 
server/graphql/invoice/src/invoice_queries.rs
server/graphql/invoice/src/lib.rs
server/service/src/invoice/mod.rs
server/service/src/invoice/query.rs

**Comment by andreievg** [comment] 2023-03-22 21:32
@bijaySussol @anildahalsussol I think this is related: https://github.com/openmsupply/open-msupply/issues/1396

@bijaySussol can you please describe how to reproduce in more detail, the steps you have to reproduce don't quite capture the configuration or details of sites making the transfer. (is it mSupply to omSupply, is it omSupply to omSupply, is it remote mSupply to remote omSupply is it central mSupply to remote omSupply ?)

I can only deduce it's for orders sent from mSupply store that is active on central to remote omSupply store, because:
* We have integration tests for omSuppyl to omSupply, and they pass
* As per issue I mention above I just did a test for remote mSupply to omSpply, it's fine
* We did notice in the PR linked to issue above this problem

**Comment by anildahalsussol** [comment] 2023-03-23 07:58
@andreievg : For me, I did initialize a new store in omSupply:
1. Create a request from omSupply to the desktop store.
2. Create a response and issue stock from desktop to omSupply.
3. Now check SI which invoice number will be initially -1. 
4. Double click and I got that error.

**Comment by bijaySussol** [comment] 2023-03-23 16:24
> @bijaySussol can you please describe how to reproduce in more detail, the steps you have to reproduce don't quite capture the configuration or details of sites making the transfer. (is it mSupply to omSupply, is it omSupply to omSupply, is it remote mSupply to remote omSupply is it central mSupply to remote omSupply ?)

Setup on Central server:

- Site ID = 2 (remote server as device type)
   - ABC store is assigned to site ID = 2
   - Type collector
   - Supplying store `General`
   - User is created to login to ABC store and is default
- Tamaki central store
   - Active on central server

Remote server and remote client is setup and pulled data for ABC store and ready to use.

Process:

- From Central server `Tamaki central store` store (Desktop)
- Created a Customer invoice to ABC store as a Stock transfer
- All done, Pulled it from remote client
- Inbound shipment created on ABC store succefully with invoice = -1
- Viewing that inbound shipment
   - Says `Failed to parse "Int": Invalid number`

Please let know if you need a images if this would add clarity on mine setup.

**Closed** 2023-04-12 22:17 UTC
Labels: bug, Section: Inbound, needs details/discussion, Priority: Normal
