### ISSUE TITLE
Numbers rows for Response and Request Requisition

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#69] opened 2022-03-31 23:10 UTC
Andrei:

".. mSupply only has one type for both, and mobile has completely different types for all number rows. mSupply it's just requisition, would be great if we can have seperate ones in omSupply, but translations become a bit tricky, i think we should just use combined type in v1. Beyond v1, we can do:

requisition maps to -> response_requisition
    a query is made when requisition type is received to see if there is request_requisition type already, if not then add request_requisition type being = number of requisition number being received, otherwise ignore
"

**Comment by Chris-Petty** [comment] 2022-06-20 02:49
@clemens-msupply @andreievg I'm not 100% sure if we're referring to mSupply `number` tables here, but we recently implemented making these syncing tables in mSupply: https://github.com/sussol/msupply/pull/10889 . This included making a field `number.store_ID` and `number_reuse.store_ID`. No points for guessing what value to assign to it 😁 .

The problem this addresses is that when you reinitialise desktop/mobiles sites at the moment you can actually lose the number sequence. So invoices would start at 1 again, or not reuse the gaps expected. Could you just use `invoices.max("invoice_number")`? Maybe. But just syncing them is more consistent and `number_reuse` is useful what it does. (IDK if this has been done in omSupply yet, if not I'd say it's low priority I still can't understand why it _really_ matters 🤣. Certainly can make orders without, making them is the important part!)

**Comment by andreievg** [comment] 2022-06-20 03:43
I think the number table logic that we've implemented so far is pretty good. The problem that's in the issue is what 'type' to used.
Requisitions in desktop (both request and response) just have one type. And in mobile they are entirely different. For new sites I think we don't have any issues, but when updating existing site t omSupply, we might need to do something tricky (and it's different for mobile and desktop)

**Comment by Chris-Petty** [comment] 2022-06-20 04:46
To clarify, you mean that each type of requisition has its own number sequence per store on mobile, but on desktop the requisition types are on the same sequence per store? Riiiight yea. 

Still, syncing them already or nah? Still a heads up that there is a new field and it's in mSupply branch `develop` so needs to be filled in for sure.

**Comment by andreievg** [comment] 2022-06-20 05:11
> To clarify, you mean that each type of requisition has its own number sequence per store on mobile, but on desktop the requisition types are on the same sequence per store? Riiiight yea.

Yep

> Still, syncing them already or nah? Still a heads up that there is a new field and it's in mSupply branch develop so needs to be filled in for sure.

Thanks, will do

**Comment by mark-prins** [comment] 2023-01-10 20:31
@andreievg @clemens-msupply @Chris-Petty : Is this resolved with #811? Can I close?

**Comment by andreievg** [comment] 2023-01-10 20:43
🙏 @mark-prins I am pretty confident it's fixed there

**Closed by andreievg** 2023-01-10 20:43 UTC
Labels: sync v5
